
services:
  api:
    build:
      context: ..
      dockerfile: Dockerfile.api
    container_name: healthcare-api
    env_file:
      - ../.env
    ports:
       - "8000:8000"


  postgres:
    image: postgres:16
    container_name: airflow-db
    env_file:
      - ../.env
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-airflow}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-airflow}
      POSTGRES_DB: ${POSTGRES_DB:-airflow}
    volumes:
      - airflow_pgdata:/var/lib/postgresql/data



  healthcare-oltp:
    image: postgres:16
    container_name: healthcare-oltp
    env_file:
      - ../.env
    environment:
      POSTGRES_USER: ${OLTP_DB_USER:-healthcare}
      POSTGRES_PASSWORD: ${OLTP_DB_PASSWORD:-healthcare}
      POSTGRES_DB: ${OLTP_DB_NAME:-healthcare}
    ports:
      - "5433:5432"
    volumes:
      - healthcare_pgdata:/var/lib/postgresql/data

  healthcare-dw:
    image: postgres:16
    container_name: healthcare-dw
    env_file:
      - ../.env
    environment:
      POSTGRES_USER: ${DW_DB_USER:-warehouse}
      POSTGRES_PASSWORD: ${DW_DB_PASSWORD:-warehouse}
      POSTGRES_DB: ${DW_DB_NAME:-healthcare_dw}
    ports:
      - "5434:5432"
    volumes:
      - warehouse_pgdata:/var/lib/postgresql/data


  airflow-init:
     
    build:
      context: ..
      dockerfile: Dockerfile.airflow
    depends_on:
      - postgres
      - healthcare-oltp
    env_file:
      - ../.env
    environment:
      DBT_PROFILES_DIR: /opt/airflow/dbt_project
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USER:-airflow}:${POSTGRES_PASSWORD:-airflow}@postgres:5432/${POSTGRES_DB:-airflow}
    command: >
      bash -c "
      airflow db migrate &&
      airflow users create
      --username admin
      --password admin
      --firstname Airflow
      --lastname Admin
      --role Admin
      --email admin@example.com
      "


  airflow-webserver:
    
    build:
      context: ..
      dockerfile: Dockerfile.airflow
    depends_on:
      - postgres
      - healthcare-oltp
    env_file:
      - ../.env
    environment:
      DBT_PROFILES_DIR: /opt/airflow/dbt_project
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
    command: airflow webserver
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ../src:/opt/airflow/src
      - ../dbt_project:/opt/airflow/dbt_project
      - ../data:/opt/airflow/data



  airflow-scheduler:
    
    build:
      context: ..
      dockerfile: Dockerfile.airflow
    depends_on:
      - postgres
      - healthcare-oltp
    env_file:
      - ../.env
    environment:
      DBT_PROFILES_DIR: /opt/airflow/dbt_project
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
    command: airflow scheduler
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ../src:/opt/airflow/src
      - ../dbt_project:/opt/airflow/dbt_project
      - ../data:/opt/airflow/data
    
volumes:
  airflow_pgdata:
  healthcare_pgdata:
  warehouse_pgdata:

networks:
  default:
    name: healthcare-network